### PR TITLE
Add karosu to challenge

### PR DESCRIPTION
**Pull request by wiredfae**

### CODE REVIEW

**Comment by wiredfae** [comment]
Hi there :)

**Comment by rxsharp** [comment]
Hello :) Thanks for doing the challenge :)

**Comment by rxsharp** [comment]
If you haven't already, please star the repo :)

**Comment by wiredfae** [comment]
done :)

**Comment by rxsharp** [comment]
Your file has been merged!!! Sorry that took a while. Thanks once again :+1:

**Comment by laurencebradford** [comment]
Yay!

On Thu, Nov 5, 2015 at 11:07 PM, Rick G notifications@github.com wrote:

> Your file has been merged!!! Sorry that took a while. Thanks once again [image:
> :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newbiecoderwarehouse/Pull-Request-Challenge/pull/44#issuecomment-154279453
> .

## 

*Laurence Bradford *
get digital skills @ learntocodewith.me

**Pull request merged**
