### PR TITLE
RBdraws

### PR DESCRIPTION
**Pull request by RBdraws**

### CODE REVIEW

**Comment by rxsharp** [comment]
Hey RBdraws! I'll be getting to your file very soon :) Thanks once again for doing this challenge :)

**Comment by rxsharp** [comment]
I'll be merging your file by 6pm tomorrow at the latest.

**Comment by rxsharp** [comment]
RBdraws! You are merged! Please star the Repo! Thanks for taking our challenge :)

**Comment by laurencebradford** [comment]
Thanks Rick :)

On Wed, Nov 4, 2015 at 4:10 PM, Rick G notifications@github.com wrote:

> RBdraws! You are merged! Please star the Repo! Thanks for taking our
> challenge :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newbiecoderwarehouse/Pull-Request-Challenge/pull/40#issuecomment-153866394
> .

## 

*Laurence Bradford *
get digital skills @ learntocodewith.me

**Pull request merged**
