### PR TITLE
Add strongdan to the challenge

### PR DESCRIPTION
**Pull request by strongdan**

### CODE REVIEW

**Comment by rxsharp** [comment]
Thanks strongdan for making a separate file! That made it easier on me to merge you file :) Thanks for taking the challenge :)

**Comment by strongdan** [comment]
No problem. I'm super new to all of this, but it's fun to pretend that I know what I'm doing. Thanks for putting up the challenge!

**Comment by rxsharp** [comment]
OPPS! lol Now it's merged! Sorry if you checked for your file lol I merged so much today and got ahead of myself lol NOW I can celebrate haha YOU ARE NOW MERGED lol

**Comment by strongdan** [comment]
If this merging all of the different pull requests becomes overwhelming for you, you might want to look at Jessica Lord's bot that automatically completes the merge step for the Git-It guide (http://jlord.us/git-it/)

**Comment by rxsharp** [comment]
Thanks! I'll take a look at it tonight and tomorrow afternoon before I start merging :)

**Pull request merged**
