### PR TITLE
Add JessZanewich to the challenge

### PR DESCRIPTION
**Pull request by JessvonEuw**

### CODE REVIEW

**Comment by rxsharp** [comment]
Currently working on your pull request :)

**Comment by rxsharp** [comment]
THANKS for making a new file and adding it to the other-responses folder!

**Comment by rxsharp** [comment]
You are merged :)

**Comment by JessvonEuw** [comment]
Thank you very much!

**Comment by rxsharp** [comment]
No problem! If you haven't already, start the repo and share it around to other newbies :)

**Pull request merged**
