### PR TITLE
add CurlsandCode to challenge

### PR DESCRIPTION
**Pull request by CurlsandCode**

### CODE REVIEW

**Comment by rxsharp** [comment]
Working on merging your file :)

**Comment by CurlsandCode** [comment]
Yay! Thanks for putting this challenge together!

**Comment by rxsharp** [comment]
No problem! Please like the the repository if you haven't already! We want to keep doing these challenges and we want to see the demand in the form of likes, retweets, shares if you can :) Thanks for you support!

**Comment by rxsharp** [comment]
And you are merged :)

**Comment by rxsharp** [comment]
ALSO lol (Sorry last one) Please like your shout out on the shout out facebook thread and I'll add your facebook name :) (Optional)

**Pull request merged**
