### PR TITLE
Add mikeyhavoc to the challenge

### PR DESCRIPTION
**Pull request by mikeyhavoc**
pull request challenge 
michael

### CODE REVIEW

**Comment by rxsharp** [comment]
Hey mikeyhavoc, you need to rename the template file to mickeyhavoc.md.. Once you do that and do another pull request, I can add you to the challenge :)

**Comment by mikeyhavoc** [comment]
ok i changed the name.
i think it is ready.

**Comment by rxsharp** [comment]
Great! I'll be adding your request soon :+1:

**Comment by rxsharp** [comment]
You are merged! Thanks for making the changes :)

**Pull request merged**
